INSERT INTO User(USERNAME, PASSWORD) VALUES ('test', 'test'); 
INSERT INTO User(USERNAME, PASSWORD) VALUES ('kim', 'kim'); 
INSERT INTO User(USERNAME, PASSWORD) VALUES ('admin', 'admin'); 
INSERT INTO User(USERNAME, PASSWORD) VALUES ('sleep', 'sleep'); 
